routes/web.php
<?php

use App\Http\Controllers\BcDescuentoController;
use App\Http\Controllers\BcLogController;
use App\Http\Controllers\BcItemController;
use App\Http\Controllers\BcProductoController;
use App\Http\Controllers\BcStockController;
use App\Http\Controllers\CommerceConnector3mController;
use App\Http\Controllers\EventoController;
use App\Http\Controllers\PasilloTiendaController;
use App\Http\Controllers\ProyectoDisenoController;
use App\Http\Controllers\PsProductoController;
use App\Http\Controllers\PublicidadCfdiController;
use App\Http\Controllers\TallaUniformeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin;
use App\Http\Controllers;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('admin/');
});

Route::get('productos/info-sat',[Admin\ProductoController::class,'searchInfoSatFromSku'])->name('info-sat-producto');
Route::post('productos/info-sat',[Admin\ProductoController::class,'showInfoSatFromSku'])->name('info-sat-producto.show');

Route::group(['middleware' => ['auth:sanctum', 'verified'], 'prefix' => 'admin'
//    , 'as' => 'admin.'
], function () {

    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::get('/', function () {
        return redirect('admin/dashboard');
    });
    Route::get('dashboard', [Admin\DashboardController::class,'index'])->name('home-admin');

    Route::get('/clearcache', function() {
        Artisan::call('cache:clear');
        return "Cache is cleared";
    });

    Route::get('envios/transportistas',[Controllers\EnvioTransportistaController::class,'index'])->name('envio-transportista.index');

    //	Pasillo-Tienda
    Route::get('producto-por-pasillo-tienda/create',[PasilloTiendaController::class,'createProductoPorPasillo'])->name('producto-por-pasillo-tienda.create');
    Route::get('producto-por-pasillo-tienda/edit/{suc?}',[PasilloTiendaController::class,'editProductoPorPasillo'])->name('producto-por-pasillo-tienda.edit');
    Route::post('producto-por-pasillo-tienda',[PasilloTiendaController::class,'updateProductoPorPasillo'])->name('producto-por-pasillo-tienda.update');

    /********************************************************************************
     * Info getetIExistenciareal1*******************************************************************************/

    /********************************************************************************
     * Cliente Distinguido
     *********************************************************************************/ 
    Route::get('solicitud-cliente-distinguido',[Controllers\SolicitudClienteDistinguidoController::class,'index'])->name('solicitud-cliente-distinguido.index');
    Route::get('solicitud-cliente-distinguido/nocd/{id}/edit',[Controllers\SolicitudClienteDistinguidoController::class,'editNoClienteDistinguido'])->name('solicitud-cliente-distinguido-nocd.edit');
    Route::post('solicitud-cliente-distinguido/nocd',[Controllers\SolicitudClienteDistinguidoController::class,'updateNoClienteDistinguido'])->name('solicitud-cliente-distinguido-nocd.update');
    Route::get('solicitud-cliente-distinguido/notificar-registrados',[Controllers\SolicitudClienteDistinguidoController::class,'notificarClientesNoCd'])->name('solicitud-cliente-distinguido-registrados.notificar');
    Route::get('solicitud-cliente-distinguido/{reference}',[Controllers\SolicitudClienteDistinguidoController::class,'show'])->name('solicitud-cliente-distinguido.show');
    // Route::post('solicitudes/clientes-distinguidos/show/{id}',[Controllers\SolicitudClienteDistinguidoController::class,'show'])->name('solicitud-cliente-distinguido.show');
    Route::get('solicitudes/clientes-distinguidos/download-files/{reference}',[Controllers\SolicitudClienteDistinguidoController::class,'download'])->name('solicitud-cliente-distinguido.download');
    
    Route::get('solicitud-cliente-distinguido-old',[Controllers\SolicitudClienteDistinguidoOldController::class,'index'])->name('solicitud-cliente-distinguido.index-old');
    Route::get('solicitud-cliente-distinguido-old/{id}',[Controllers\SolicitudClienteDistinguidoOldController::class,'show'])->name('solicitud-cliente-distinguido.show-old');
    Route::get('solicitud-cliente-distinguido-old/download-files/{id}',[Controllers\SolicitudClienteDistinguidoOldController::class,'download'])->name('solicitud-cliente-distinguido.download-old');

   /********************************************************************************
    * BC-PS
    *********************************************************************************/
    Route::get('bc/productos/listarDiferenciasBcPs',[Controllers\Admin\LSCProductoController::class,'listarDiferenciasBcPs'])->name('bc.productos.listarDiferenciasBcPs.index');
    Route::get('bc/productos/corregirDiferenciasBcPs',[Controllers\Admin\LSCProductoController::class,'corregirDiferenciasBcPs'])->name('bc.productos.corregirDiferenciasBcPs.index');
    
    /********************************************************************************
     * Entregas Informacion Productos Proveedor
     *********************************************************************************/
    // Route::get('productos/proveedor/informacion/entrega',[Controllers\])

    /********************************************************************************
     * Redpack
     *********************************************************************************/
    Route::get('rastreo/',[Controllers\Admin\RedpackController::class,'searchRastreo'])->name('rastreo.search');
    Route::get('rastreo/redpack/{id?}',[Controllers\Admin\RedpackController::class,'showRastreo'])->name('rastreo.show');

    Route::get('coti-envio/redpack',[Controllers\Admin\RedpackController::class,'cotizarEnvioForm'])->name('redpack.coti-envio');
    Route::post('coti-envio/redpack',[Controllers\Admin\RedpackController::class,'cotizarEnvioShow'])->name('redpack.coti-envio.show');

    /********************************************************************************
     * Proyectos de Diseño
     *********************************************************************************/
    Route::get('proyectos-diseno/',[ProyectoDisenoController::class,'index'])->name('proyectos-diseno.index');
    Route::get('proyectos-diseno/{id}',[ProyectoDisenoController::class,'show'])->name('proyectos-diseno.show');
    Route::get('proyectos-diseno/{id}/eventos/',[ProyectoDisenoController::class,'indexEventos'])->name('eventos-proyecto-diseno.index');

    Route::get('proyectos-diseno/{id}/eventos/create',[EventoController::class,'create'])->name('evento-proyecto-diseno.create');
    Route::post('proyectos-diseno/{id}/eventos',[EventoController::class,'store'])->name('evento-proyecto-diseno.store');


    /********************************************************************************
     * Sincronizacion Magic
     *********************************************************************************/
    Route::get('ps/productos/cambio-precio-compras',[PsProductoController::class,'createCambioPrecioProductoCompras'])->name('cambio-precios-compras.create');
    Route::post('ps/productos/cambio-precio-compras',[PsProductoController::class,'storeCambioPrecioProductoCompras'])->name('cambio-precios-compras.store');
//    Route::post('proyectos-diseno/{id}/eventos',[EventoController::class,'store'])->name('evento-proyecto-diseno.store');

    /******************************************************************************
     * Integracion con BC
     *******************************************************************************/
    Route::get('bc/logs',[BcLogController::class,'index'])->name('bc-log.index');
    Route::get('bc/{id}/edit',[BcLogController::class,'index'])->name('bc-log.edit');

    Route::get('bc/productos',[BcProductoController::class,'index'])->name('bc-producto.index');

    /******************************************************************************
     * Tallas Uniformes
     *******************************************************************************/
    Route::get('uniformes/tallas',[TallaUniformeController::class,'create'])->name('tallas-uniformes.create');
    Route::post('uniformes/tallas',[TallaUniformeController::class,'store'])->name('tallas-uniformes.store');

});
// API BC-HO
Route::get('bc/getAndSendStockBcFromDB',[BcStockController::class,'getAndSendStockBcFromDB']);
Route::get('bc/getStockFromDbSp',[BcStockController::class,'getStockFromDbSp'])->name('bc.index.stock-ecbcsp');
Route::get('bc/api/getStockBcFromBcApi/{id?}',[BcStockController::class,'getStockBcFromBcApi'])->name('bc.show.stock-ecbcapi');
Route::get('bc/api/getAllStockBcFromBcApi/{id?}',[BcStockController::class,'getAllStockBcFromBcApi'])->name('bc.show.stock-bcapi');
Route::get('bc/api/showdiferenciaPreciosTpvGral',[BcItemController::class,'showDiferenciaPreciosTpvGral'])->name('bc.index.diferencia-precios-tpvgral');
Route::get('bc/api/spGetItemsList1',[BcItemController::class,'index'])->name('bc-item-list1.index');
Route::get('bc/api/sincListaOfertaDescuentoBcPS',[BcDescuentoController::class,'sincListaOfertaDescuentoBcPS']);
Route::get('bc/api/descuentos/{codigo?}',[BcDescuentoController::class,'getDescuentosFromBcApi']);
Route::get('bc/api/exsapi/{codigo?}',[BcStockController::class,'getExsapiFromCodigo']);
//
Route::get('bc/producto/sincpreciosbcps',[BcItemController::class,'sincPreciosProductosBcPs'])->name('sinc_precios_bcps');
Route::get('bc/producto/sincstockbcps',[BcStockController::class,'sincStockProductosBcPs'])->name('sinc_stock_bcps');

app/Models/SolicitudClienteDistinguido.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SolicitudClienteDistinguido extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $table = 'solicitudes_cliente_distinguido';
    protected $guarded = ['estado'];
    public function scopeRegistradosSinNotificar($query)
    {
        // return $query->whereNotNull('no_cd')->whereNull('fecha_notificacion')->where('fecha_registro','<',Carbon::now()->subDay());
        return $query->whereNotNull('no_cd')->whereNull('fecha_notificacion')->where('fecha_registro','<',Carbon::today()->startOfDay());
    }
    public function getFechaRegistroAttribute($date) {
        return Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('H:i:s');
    }
    public function getTituloFormattedAttribute()
    {
        $titulo = Str::ucfirst($this->titulo);
        if($this->titulo == 'dr' || $this->titulo == 'dra') {
            return $titulo . '.';
        }
        return $titulo;
    }
    public function getTituloNombreFormattedAttribute()
    {
        if($this->titulo == 'dr' || $this->titulo == 'dra') {
            return $this->titulo_formatted . ' ' . $this->nombre;
        }
        return $this->nombre;
    }
    public function getEspecialidadFormattedAttribute()
    {
        $especialidad = EspecialidadMedica::find($this->id_especialidad_medica);
        $especialidad = $especialidad ? $especialidad->nombre : null;
        
        return Str::ucfirst($especialidad);
    }
    public function getEstadoFormattedAttribute()
    {
        $estado = DB::connection('production_presta')->table('state')->select('name')->where('id_country',145)->where('id_state',$this->id_state)->first();        
        
        return Str::upper($estado->name);
    }
    public function getFechaNacimientoFormattedAttribute()
    {
        return Carbon::parse($this->fecha_nacimiento)->format('d-M-Y');
    }
    public function getEstatusTextAttribute()
    {

        if(!$this->no_cd)
        {
            $estatus = 'Pendiente';

        } elseif ($this->no_cd && !(bool)$this->fecha_notificacion)
        {
            $estatus = 'Registrado';

        } elseif ($this->no_cd && (bool)$this->fecha_notificacion)
        {
            $estatus = 'Terminado';
        }
        return $estatus;
    }
    public function setCurpAttribute($value)
    {
        $this->attributes['curp'] = Str::upper($value);
    }
    public function setNombreAttribute($value)
    {
        $this->attributes['nombre'] = Str::upper($value);
    }
    public function setEmailAttribute($value)
    {
        $this->attributes['email'] = Str::upper($value);
    }
    public function setDireccionAttribute($value)
    {
        $this->attributes['direccion'] = Str::upper($value);
    }
    public function setMunicipioAttribute($value)
    {
        $this->attributes['municipio'] = Str::upper($value);
    }
    public function setColoniaAttribute($value)
    {
        $this->attributes['colonia'] = Str::upper($value);
    }
}

resources/views/solicitud-cliente-distinguido/_part-show-tocliente.blade.php
@if($data->to_cliente && $data->is_email)
<div class="info-box bg-success">
    @if(!$data->is_email)
    <span class="info-box-icon bg-success"><i class="far fa-thumbs-up"></i></span>
    @endif
    <div class="info-box-content">
    <span class="info-box-number">{{ $data->subtitulo ?? '' }}</span>
    <span class="info-box-text">
    <span class="sub-info-box"></span>
        <ul>
            <li>La solicitud será revisada y procesada en las próximas horas. El tiempo aproximado para obtener su registro es de 2 a 3 días hábiles.</li> 
            <li>En ese periodo de tiempo, usted recibirá una notificación indicándole el estatus de la solicitud al correo electrónico que usó al registrarse.</li>
            <li>Revise muy bien su bandeja de entrada, spam o correo no deseado ya que a veces puede que llegué ahí el mensaje.</li>
            <li>Si pasado el tiempo regular de registro, no recibe notificación alguna, le pedimos de favor se comunique al 55-5578-1958 para preguntar por el status de la solicitud.</li> 
            <li>Al recibir la notificación por correo, en caso de que haya sido positivo su registro, se le proporcionará su nuevo No. de Cliente Distinguido.</li>
            <li>Una vez conociendo usted su No. de Cliente Distinguido, podrá acudir a cualquiera de nuestras tiendas para recibir el plástico físicamente.</li> 
            <li><strong>Muy importante:</strong> La entrega del plástico así como la aplicación de su descuento en cualquier compra, será posible hasta que se le asigne en sistema un numero de Cliente Distinguido, no antes.</li> 
        </ul>
        <span class="sub-info-box">¡Agradecemos su preferencia para Lanceta HG!</span>
    </span>
    </div>
</div>
@elseif ($data->is_email)
<div class="info-box bg-info">
    @if(!$data->is_email)
    <span class="info-box-icon bg-info"><i class="far fa-inbox"></i></span>
    @endif
    <div class="info-box-content">
    <span class="info-box-number">{{ $data->subtitulo ?? '' }}</span>
    <span class="info-box-text">
    <span class="sub-info-box"></span>
        <ul>
            <li>Si el correo registrado está asociado a un Cliente Distinguido actual, proceder a notificar al cliente.</li> 
            <li>Si la documentación es errónea o incompleta, contactar al cliente y solicitarle lo faltante. Posteriormente, adjuntar la documentación a la solicitud.</li>
            <li><strong>Muy importante:</strong> Notificar al cliente cuando haya alguna inconsistencia en el proceso de registro de No. de Cliente Distinguido.</li> 
        </ul>
        <span class="sub-info-box">&nbsp;</span>

    </span>
    </div>
</div>
@endif

resources/views/solicitud-cliente-distinguido/_part-show.blade.php
<table border="0" cellpadding="0" cellspacing="0" width="100%" id="headerMessage" class="datos">
    <tr>
        <td align="center">
            <div class="logo-container">
                <img src="https://www.lancetahg.com.mx/img/store-logo-default-xs-1496332314.png" alt="">
            </div>
        </td>
    </tr>
</table>

@include('solicitud-cliente-distinguido._part-show-tocliente')

<table border="0" cellpadding="0" cellspacing="0" width="100%" id="mainContent" class="datos">
    <tr>
        <td align="left" valign="center" >
            <table style="width:100%;">
                <tr>
                    <td valign="top" align="left" style="text-align:left;vertical-align:top;">
                        <table style="width:100%">
                            <tr>
                                <td>
                                    <span><strong>Solicitud #{{ $data->scd->reference ?? '' }}</strong></span>
                                </td>
                                <td align="right" valign="top" style="padding: 0;">
                                    <strong><p style="color: #686969;font-family: Arial,sans-serif;font-size: 12px; margin: 0 !important;">Fecha de Registro: {{ \Illuminate\Support\Carbon::parse($data->scd->created_at)->format('d-m-Y H:m:s') }}</p></strong>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">&nbsp;</td>
                            </tr>
                            <tr>
                                <td colspan="2"><h3>Datos Generales</h3></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Especialidad Médica:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->especialidad_formatted  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Nombre:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->titulo_nombre_formatted ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">CURP:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->curp  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Fecha de Nacimiento:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->fecha_nacimiento_formatted  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Teléfono:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->telefono  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Email:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->email  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td colspan="2">&nbsp;</td>
                            </tr>
                            <tr>
                                <td colspan="2"><h3>Datos de Dirección</h3></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Dirección:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->direccion  ?? 'N/A' }}</span></td>
                            </tr>

                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Colonia o población:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->colonia  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Alcaldía o municipio:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->municipio  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Estado:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->estado_formatted  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td valign="top" style="width:40%;  vertical-align:top;"><span class="nombre-campo">Código Postal:</span></td>
                                <td valign="top" style="width:60%; vertical-align:top;"><span>{{ $data->scd->codigo_postal  ?? 'N/A' }}</span></td>
                            </tr>
                            <tr>
                                <td colspan="2">&nbsp;</td>
                            </tr>
                            <tr>
                                <td colspan="2"><h3>Documentación</h3></td>
                            </tr>

                            <tr>
                                <td colspan="2">
                                    <table width="100%" class="documentacion">
                                        <tr>
                                            <td style="width: 50%;">
                                                <div class="documento">
                                                    <span class="nombre-campo">Identificación Oficial:</span>
                                                    <div>
                                                        <img src="{!! $data->docs['ine'] !!}" alt="{{$data->scd->ife}}" title="{{$data->scd->ife}}">
                                                    </div>
                                                    <span>{{ \Str::limit($data->scd->ine,30) ?? 'N/A' }}</span>
                                                </div>

                                            </td>
                                            <td style="width: 50%;">
                                                <div class="documento">
                                                    <span class="nombre-campo">Comprobante de Domicilio:</span>
                                                    <div>
                                                        <img src="{!! $data->docs['comprobante'] !!}" alt="{{ $data->scd->comprobante }}" title="{{ $data->scd->comprobante }}">
                                                    </div>
                                                    <span>{{ \Str::limit($data->scd->comprobante,30) ?? 'N/A' }}</span>
                                                </div>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            @if(!$data->to_cliente)
                            <tr>
                                <td colspan="2">
                                    <a href="{{ route('solicitud-cliente-distinguido.download',[$data->scd->reference]) }}" class="btn btn-sm btn-info"><i class="fa fa-download fa-2x"></i> Descargar documentación</a>
                                </td>
                            </tr>
                            @endif

                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

resources/views/solicitud-cliente-distinguido/edit-nocd.blade.php
<button type="button" class="close" data-dismiss="modal" aria-label="Close" style="position: absolute;top: 10px;right: 20px;">
    <span aria-hidden="true">&times;</span>
</button>
<h3 class="text-center" style="margin-top: 20px;">{{ $title }}</h3>
<div class="scd-container" style="box-sizing: content-box; width: 100%;">
    <div class="card-header text-center">
        <h4>Solicitud No. {{ $cd->id }} perteneciente a: </br>{{ $cd->nombre }}</h4>
        <div class="errores">
            <ul id="list-errores"></ul>
        </div>
    </div>
    {!! Form::open([
        'route' => 'solicitud-cliente-distinguido-nocd.update',
        'id'=> 'cdno-form',
    ],) !!}
        <input type="hidden" name="reference" id="reference" value="{{ $cd->reference }}">
        <div class="card-body">     
            <section class="header_form mb-4">
                <p>Los campos con <sup>*</sup> son requeridos</p>
            </section>

            <section class="mb-4">
                <h2 class="collapse">No. de Cliente</h2>
                <div class="row">    
                    <div class="col-12 col-sm-10 col-md-10">
                        <div class="form-group">
                            <label for="no_cd">No. de Cliente Distinguido: <sup>*</sup></label>
                            <div class="input-group">
                                <input class="form-control" type="text" id="no_cd" name="no_cd" value="{{ old('codigo_postal') }}" placeholder="Sin prefijo 'CD' | 2 ... 999999" required />
                            </div>
                            @error('no_cd')
                                <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                    </div>
                </div>
            </section>

        </div>
        <div class="card-footer">
            <button type="button" class="btn btn-block btn-info float-right" id="btnRegistrar">Registrar No. de Cliente</button>
        </div>
    {!! Form::close() !!}
</div>

<script>
    var token = '{{ csrf_token() }}';
    var ref = '{{ $cd->reference }}'
    var url = uri + '/nocd';
    var error_bag = $('#list-errores');
    $(document).ready( function () {
        $(document).on('click','#btnRegistrar',function(e) {
            e.preventDefault();

            var data = {
                _token: '{{ csrf_token() }}',
                reference: '{{ $cd->reference }}',
                no_cd: $('#no_cd').val(),
                id: '{{ $cd->id }}'
            }
            
            $.ajax({
                type: 'POST',
                url: url,
                cache: false,
                data: data,
                dataType: 'json',
                success: function (response) {
                    
                    // console.log(response);
                    if(response.status == 400)
                    {
                        if($(error_bag).is(':hidden'))
                            $(error_bag).show()
                        $(error_bag).html('');
                        $(error_bag).addClass('list-unstyled alert alert-danger');
                        $.each(response.messages, function(inputs,valores) {
                            $.each(valores, function(k,error) {
                                $(error_bag).append('<li>'+ error +'</li>');
                            })
                        })
                        setTimeout(function(){
                          $(error_bag).fadeOut();
                        }, 1000);
                    }
                    else if (response.status == 200)
                    {
                        if($(error_bag).is(':hidden'))
                            $(error_bag).show()
                        if($(error_bag).hasClass('alert-danger'))
                            $(error_bag).removeAttr('class');
                        $(error_bag).html('');
                        $(error_bag).addClass('list-unstyled alert alert-success');
                        $(error_bag).append('<li>'+ response.message.message +'</li>');
                        // $('#Modal').modal('hide');
                        
                        setTimeout(function(){
                          $('#Modal').modal('hide');
                          window.location.href = uri;
                        }, 1000);
                    }

                    // $('.modal-content').html(response.Xml);
                }
            });
        });

    });

</script>